<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SSLConfiguration.Contracts\SSLConfiguration.Contracts.csproj" />
    <ProjectReference Include="..\SSLConfiguration.Infrastructure\SSLConfiguration.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Resources.resx">
      <Generator></Generator>
      <StronglyTypedFileName></StronglyTypedFileName>
    </EmbeddedResource>
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
  <ItemGroup>
    <Reference Include="VerisignGateway">
      <HintPath>..\ExternalDLL\VerisignGateway.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
